[package]
name = "spr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
tachyonfx = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
